baseURL = "https://welder-mona-71407.netlify.com/"
languageCode = "en-us"
title = "Rubens Site"
theme = "ananke"
SectionPagesMenu = "main"
[params]
twitter = "https://twitter.com/t4ostra"
featured_image = "/images/image.jpg"